config/routes.rb
Rails.application.routes.draw do
  get 'bookings/index'
  root to: 'events#index'
  devise_for :users
  resources :events do 
    resources :bookings, only: [:create, :new]
  end
  get 'my_events', to: 'events#current_user_events'
  get 'my_bookings', to: 'bookings#index'
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :event

  def generate_reference
    loop do
      random_code = 6.times.map { rand(0..9) }.join
      break random_code if Booking.where(ticket_number: random_code).count.zero?
    end
  end
end

app/models/event.rb
class Event < ApplicationRecord
  extend FriendlyId
  lock_optimistically
  friendly_id :name, use: :slugged

  belongs_to :user
  has_many :bookings, dependent: :destroy

  before_save :set_remaining_ticket, if: -> { new_record? }

  validates :name, presence: true, uniqueness: true
  validates :description, presence: true, length: { minimum: 10 }
  validates :location, :date_and_time, presence: true
  validates :total_tickets, presence: true, numericality: { only_integer: true, greater_than: 0 }

  def available_for_booking?
    remaining_ticket.positive?
  end

  protected

  def set_remaining_ticket
    self.remaining_ticket = total_tickets
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :events, dependent: :destroy
  has_many :bookings, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  respond_to :json, :html, :js

  skip_before_action :verify_authenticity_token
  protect_from_forgery with: :null_session
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_event, only: :create

  def index
    @bookings = Rails.cache.fetch("bookings", expires_in: 5.minutes) do
      current_user.bookings.includes(:event)
    end
  end

  def new
    @event = Event.friendly.find(params[:event_id])
    @booking = @event.bookings.new
  end

  def create
    return redirect_to new_event_booking_path(@event), alert: 'Event is not available for booking' unless @event.available_for_booking?
    return redirect_to new_event_booking_path(@event), alert: "Only #{@event.remaining_ticket} tickets are available for Event" if @event.remaining_ticket < bookings_params[:ticket_quantity].to_i

    @booking = BookingService.new(current_user, @event, bookings_params).call
    if @booking.present?
      render json: { message: 'Booking created successfully' }, status: :ok
      # @message = 'Booking created successfully'
      # respond_to do |format|
      #        format.turbo_stream
      #    end
    else
      render :new
    end
  end

  protected

  def find_event
    @event = Event.friendly.find(params[:event_id])
  end

  def bookings_params
    params.require(:booking).permit(:event_id, :ticket_quantity)
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  before_action :set_event, only: %i[show edit update destroy]

  def index
    @events = Rails.cache.fetch('events', expires_in: 1.hour) do
      Event.all.order("name ASC")
    end
  end

  def current_user_events
    @events = Rails.cache.fetch('current_user_events', expires_in: 1.hour) do
      current_user.events.order(created_at: :desc)
    end
  end

  def show; end

  def new
    @event = Event.new
  end

  def create
    @event = current_user.events.create(event_params)
    if @event.save
      redirect_to @event, notice: 'Event was successfully created.'
    else
      render :new
    end
  end

  def edit; end

  def update
    if @event.update(event_params)
      redirect_to @event, notice: 'Event was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @event.destroy
    redirect_to events_url, notice: 'Event was successfully destroyed.'
  end

  private

  def set_event
    @event = Event.friendly.find(params[:id])
  end

  def event_params
    params.require(:event).permit(:name, :description, :location, :date_and_time, :total_tickets, :user_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def autoredirect_to(url)
        link = tag.a(href: url,hstyle: 'display:none;', data: {controller: "booking-form"}, turbo_cache: false)
        turbo_stream.append_all('notification') { link }
    end
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/bookings/_form.html.erb
<!-- Modal toggle -->
<%# <button data-modal-target="authentication-modal" data-modal-toggle="authentication-modal" class="block text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800" type="button">
  Toggle modal
</button> %>

<!-- Main modal -->
<div id="authentication-modal" tabindex="-1" aria-hidden="true" class="hidden overflow-y-auto overflow-x-hidden fixed top-0 right-0 left-0 z-50 justify-center items-center w-full md:inset-0 h-[calc(100%-1rem)] max-h-full">
    <div class="relative p-4 w-full max-w-md max-h-full">
        <!-- Modal content -->
        <div class="relative bg-white rounded-lg shadow dark:bg-gray-700">
            <!-- Modal header -->
            <div class="flex items-center justify-between p-4 md:p-5 border-b rounded-t dark:border-gray-600">
                <h3 class="text-xl font-semibold text-gray-900 dark:text-white">
                    Sign in to our platform
                </h3>
                <button type="button" class="end-2.5 text-gray-400 bg-transparent hover:bg-gray-200 hover:text-gray-900 rounded-lg text-sm w-8 h-8 ms-auto inline-flex justify-center items-center dark:hover:bg-gray-600 dark:hover:text-white" data-modal-hide="authentication-modal">
                    <svg class="w-3 h-3" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 14 14">
                        <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 1 6 6m0 0 6 6M7 7l6-6M7 7l-6 6"/>
                    </svg>
                    <span class="sr-only">Close modal</span>
                </button>
            </div>
            <!-- Modal body -->
            <div class="p-4 md:p-5">
                <form class="space-y-4">
                    <div>
                        <label for="ticket_quantity" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Ticket Quantity</label>
                        <input type="text" name="ticket_quantity" id="quantity" class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-600 dark:border-gray-500 dark:placeholder-gray-400 dark:text-white" placeholder="1" required />
                    </div>
                    <button type="submit" data-action="booking-form#saveBooking" class="w-full text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">Book</button>
                </form>
            </div>
        </div>
    </div>
</div> 

app/views/bookings/create.turbo_stream.erb
<%=turbo_stream.update "notification" do%>
  <%= @message%>
  <%= link_to "Back to events", my_bookings_path, data: {controller: "booking-form"}, turbo_cache: false, class: "hidden"  %>
<%end%>

app/views/bookings/index.html.erb
  <section class="text-blueGray-700">
    <% if @notification.present? %>
      <div class="alert notice">
        <%= @notification %>
      </div>
    <% end %>
    <div class="bg-blueGray-50 flex flex-col gap-8 bg-[#b5c2d1]">
      <div class="text-black">
        <div class="flex flex-wrap justify-between">
          <div class="text-lg shadow-md bg-white text-[#264C79] lg:px-10 md:w-80 h-28 pb-2 flex flex-col items-center justify-center rounded w-fit">
            <%= @bookings.count %> Bookings
          </div>
        </div>
      </div>

      <div class="employees-list w-[100%] bg-white rounded-lg overflow-hidden">
        <h1 class="text-2xl text-center font-semibold mb-4 pt-4">List of your bookings</h1>
        <div class="overflow-x-auto">
          <div class="inline-block min-w-full py-2 sm:px-6 lg:px-8">
            <div class="overflow-hidden">
              <table class="min-w-full text-left text-sm font-light">
                <thead class="border-b bg-white font-medium justify-between">
                  <tr>
                    <th scope="col" class="px-6 py-4">N</th>
                    <th scope="col" class="px-6 py-4">Event Name</th>
                    <th scope="col" class="px-6 py-4">Event location</th>
                    <th scope="col" class="px-6 py-4">Event Date & Time</th>
                    <th scope="col" class="px-6 py-4">Booking ticket</th>
                    <th scope="col" class="px-6 py-4">Booked at</th>
                  </tr>
                </thead>
                <tbody>
                  <% @bookings.each.with_index(1) do |bk, index| %>
                    <tr class="<%= cycle('bg-white ', 'bg-neutral-100 justify-between') %>">
                      <td class="whitespace-nowrap px-6 py-4"><%= index %></td>
                      <td class="whitespace-nowrap px-6 py-4"><%= bk&.event&.name %></td>
                      <td class="whitespace-nowrap px-6 py-4"><%= bk&.event&.location %></td>
                      <td class="whitespace-nowrap px-6 py-4"><%= bk&.event&.date_and_time.strftime("%B %d, %Y %I:%M %p") %></td>
                      <td class="whitespace-nowrap px-6 py-4"><%= bk&.ticket_number %></td>
                      <td class="whitespace-nowrap px-6 py-4"><%= bk.created_at.strftime('%d %b %Y') %></td>
                    </tr>
                  <% end %>
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>

app/views/bookings/new.html.erb
<%= turbo_frame_tag "modal" do %>
  <div class="">
    <%= render partial: "bookings/form" %>
  </div>
<% end %>

app/views/events/_form.html.erb
<div class="container mx-auto p-4 w-1/2 mx-auto">
  <%= form_with(model: [@user, @event], local: true, data: { turbo: false }) do |form| %>
    <% if @event.errors.any? %>
      <%= render partial: "shared/form_errors", locals: { record: @event } %>
    <% end %>

    <div class="mb-4">
      <%= form.label :name, "Event Name", class: "block text-gray-700 text-sm font-bold mb-2" %>
      <%= form.text_field :name, class: "w-full px-3 py-2 border rounded-md" %>
    </div>

    <div class="mb-4">
      <%= form.label :description, "Description", class: "block text-gray-700 text-sm font-bold mb-2" %>
      <%= form.text_area :description, class: "w-full px-3 py-2 border rounded-md" %>
    </div>

    <div class="mb-4">
      <%= form.label :location, "Location", class: "block text-gray-700 text-sm font-bold mb-2" %>
      <%= form.text_field :location, class: "w-full px-3 py-2 border rounded-md" %>
    </div>

    <div class="mb-4">
      <%= form.label :datetime, "Date & Time", class: "block text-gray-700 text-sm font-bold mb-2" %>
      <%= form.datetime_local_field :date_and_time, class: "w-full px-3 py-2 border rounded-md" %>
    </div>

    <div class="mb-4">
      <%= form.label :total_tickets, "Total Tickets", class: "block text-gray-700 text-sm font-bold mb-2" %>
      <%= form.number_field :total_tickets, class: "w-full px-3 py-2 border rounded-md" %>
    </div>

    <div class="mt-4">
      <%= form.submit @event.persisted? ? "Update Event" : "Create Event", class: "px-4 py-2 bg-blue-500 text-white rounded-md" %>
    </div>
  <% end %>
</div>

app/views/events/current_user_events.html.erb
<div class="container mx-auto mt-4">
  <h1 class="font-bold text-4xl mb-4">Events</h1>
  
  <% @events.each do |event| %>
    <div class="bg-white shadow-md rounded-md p-4 mb-4">
      <h2 class="text-xl font-semibold mb-2">Name: <%= event.name %></h2>
      <p class="text-gray-700 mb-2">Description:  <%= event.description %></p>
      <p class="text-gray-600 mb-2">Location: <%= event.location %></p>
      <p class="text-gray-600 mb-2">Date & Time: <%= event.date_and_time.strftime("%B %d, %Y %I:%M %p") %></p>
      <p class="text-gray-600">Available Tickets: <%= event.total_tickets %></p>
    </div>
  <% end %>
</div>

app/views/events/edit.html.erb
<%= render partial: "events/form" %>

app/views/events/index.html.erb
<div class="container mx-auto mt-4" data-controller="booking-form">
  <%= render "bookings/form"%>
<div id="notification"></div>
  <h1 class="font-bold text-4xl mb-4">Events</h1>
  
  <% @events.each do |event| %>
    <div class="bg-white shadow-md rounded-md p-4 mb-4">
      <h2 class="text-xl font-semibold mb-2">Name: <%= event.name %></h2>
      <p class="text-gray-700 mb-2">Description:  <%= event.description %></p>
      <p class="text-gray-600 mb-2">Location: <%= event.location %></p>
      <p class="text-gray-600 mb-2">Date & Time: <%= event.date_and_time.strftime("%B %d, %Y %I:%M %p") %></p>
      <p class="text-gray-600">Available Tickets: <%= event.remaining_ticket %></p>

      <% if event.remaining_ticket.zero? %>
        <p class="text-red-500 mb-2">No tickets available anymore for this event.</p>
      <% elsif event.date_and_time < Time.now %>
        <p class="text-red-500 mb-2">Event is in the past</p>
      <% else %>
        <%= link_to "Book Event", new_event_booking_path(event_id: event.id), data: {action: "booking-form#showForm"},"data-event" => event.id, method: :get, class: "bg-blue-500 text-white px-4 py-2 rounded-md" %>
      <% end %>
    </div>
  <% end %>

</div>

app/views/events/new.html.erb
<%= render partial: "events/form" %>

app/views/events/show.html.erb
<div class="container mx-auto p-4 w-1/2 mx-auto">
  <h1 class="font-bold text-4xl mb-4">Event Details</h1>
  
  <div class="mb-4">
    <p class="block text-gray-700 text-sm font-bold mb-2">Event Name</p>
    <p><%= @event.name %></p>
  </div>

  <div class="mb-4">
    <p class="block text-gray-700 text-sm font-bold mb-2">Description</p>
    <p><%= @event.description %></p>
  </div>

  <div class="mb-4">
    <p class="block text-gray-700 text-sm font-bold mb-2">Location</p>
    <p><%= @event.location %></p>
  </div>

  <div class="mb-4">
    <p class="block text-gray-700 text-sm font-bold mb-2">Date & Time</p>
    <p><%= @event.date_and_time.strftime("%B %d, %Y %I:%M %p") %></p>
  </div>

  <div class="mb-4">
    <p class="block text-gray-700 text-sm font-bold mb-2">Total Tickets</p>
    <p><%= @event.total_tickets %></p>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EventTicketBooking</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/2.2.1/flowbite.turbo.min.js"></script>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
  </head>

   <body class="">
      <p class="notice text-green-300" style="display: block;"><%= notice %></p>
      <p class="alert" style="display: block;"><%= alert %></p>
        <main>
          <%= render partial: 'shared/header' %>
          <%= turbo_frame_tag "modal"%>
          <%= yield %>
        </main>
    </body>
</html>

app/views/shared/_form_errors.html.erb
<% if record.errors.any? %>
  <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
    <h2><%= pluralize(record.errors.count, "error") %> prohibited this record from being saved:</h2>

    <ul>
      <% record.errors.each do |error| %>
        <li><%= error.full_message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_header.html.erb
<nav class="bg-white border-gray-200 dark:bg-gray-900">
  <div class="max-w-screen-xl flex flex-wrap items-center justify-between mx-auto p-4">
    <a href="/" class="flex items-center space-x-3 rtl:space-x-reverse">
        <img src="https://flowbite.com/docs/images/logo.svg" class="h-8" alt="Flowbite Logo" />
        <span class="self-center text-2xl font-semibold whitespace-nowrap dark:text-white">Home</span>
    </a>
 
    <div class="hidden w-full md:block md:w-auto" id="navbar-default">
      <ul class="font-medium flex flex-col p-4 md:p-0 mt-4 border border-gray-100 rounded-lg bg-gray-50 md:flex-row md:space-x-8 rtl:space-x-reverse md:mt-0 md:border-0 md:bg-white dark:bg-gray-800 md:dark:bg-gray-900 dark:border-gray-700">
      
        <li class="block py-2 px-3 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0 dark:text-white md:dark:hover:text-blue-500 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent">
            <%= link_to "New Event", new_event_path %>
        </li>

        <li class="block py-2 px-3 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0 dark:text-white md:dark:hover:text-blue-500 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent">
           <% if current_user %>
              <button>
                <li class="block py-2 px-3 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0 dark:text-white md:dark:hover:text-blue-500 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent">
                    <%= link_to "My Events", my_events_path %>
                </li>
              </button>

               <button>
                <li class="block py-2 px-3 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0 dark:text-white md:dark:hover:text-blue-500 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent">
                    <%= link_to "My Bookings", my_bookings_path %>
                </li>
              </button>

                <button>
                <li class="block py-2 px-3 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0 dark:text-white md:dark:hover:text-blue-500 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent">
                  <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
                </li>
                </button>
            <% else %>
              <button>
                <li class="block py-2 px-3 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0 dark:text-white md:dark:hover:text-blue-500 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent">
                    <%= link_to "Sign up", new_user_registration_path %>
                </li>
              </button>
              
              <button>
                <li class="block py-2 px-3 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0 dark:text-white md:dark:hover:text-blue-500 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent">
                  <%= link_to "Login", new_user_session_path %>
                </li>
              </button>
            <% end %>
        </li>
      </ul>
    </div>
  </div>
</nav>